/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dataclasses.ReportContentDto;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import navigationCofiguration.NavigationConstants;
import navigationCofiguration.NavigationController;
import services.impl.DashboardServiceImpl;
import services.impl.RegistrationServiceImpl;
import services.interfaces.RegistrationService;
import utils.Arguments;
import utils.KeyValuePair;

/**
 *
 * @author shinu.k
 */
public class DashboardScreen extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardScreen() {
        initComponents();
        loadContractReport();
        loadLaborWageReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPMaster = new javax.swing.JPanel();
        btnQuotation = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnMaterial = new javax.swing.JButton();
        btnLabor = new javax.swing.JButton();
        btnContract = new javax.swing.JButton();
        btnLaborCharge = new javax.swing.JButton();
        jPSettings = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        jPContractReport = new javax.swing.JScrollPane();
        jPLaborReport = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("appResources/Strings"); // NOI18N
        setTitle(bundle.getString("Dashboard_Screen")); // NOI18N
        setAlwaysOnTop(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        jPMaster.setToolTipText("");

        btnQuotation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/archive.png"))); // NOI18N
        btnQuotation.setText(bundle.getString("Quotation_Menu_Caption")); // NOI18N
        btnQuotation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuotation.setPreferredSize(new java.awt.Dimension(100, 100));
        btnQuotation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuotationActionPerformed(evt);
            }
        });

        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/customer.png"))); // NOI18N
        btnCustomer.setText(bundle.getString("Customer_Menu_Caption")); // NOI18N
        btnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/material.png"))); // NOI18N
        btnMaterial.setText(bundle.getString("Material_Menu_Caption")); // NOI18N
        btnMaterial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaterial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialActionPerformed(evt);
            }
        });

        btnLabor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/labor.png"))); // NOI18N
        btnLabor.setText(bundle.getString("Labor_Menu_Caption")); // NOI18N
        btnLabor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLabor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaborActionPerformed(evt);
            }
        });

        btnContract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/contract.png"))); // NOI18N
        btnContract.setText(bundle.getString("Contract_Menu_Caption")); // NOI18N
        btnContract.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContract.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContractActionPerformed(evt);
            }
        });

        btnLaborCharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/wage.png"))); // NOI18N
        btnLaborCharge.setText(bundle.getString("Labor_Charge_Menu_Caption")); // NOI18N
        btnLaborCharge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaborCharge.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLaborCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaborChargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMasterLayout = new javax.swing.GroupLayout(jPMaster);
        jPMaster.setLayout(jPMasterLayout);
        jPMasterLayout.setHorizontalGroup(
            jPMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMasterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLabor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnContract, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLaborCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPMasterLayout.setVerticalGroup(
            jPMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMasterLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLaborCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnContract, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLabor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("MasterTabCaption"), jPMaster); // NOI18N

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/exit.png"))); // NOI18N
        btnExit.setText(bundle.getString("Exit_Menu_Caption")); // NOI18N
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appResources/settings.png"))); // NOI18N
        btnSettings.setText(bundle.getString("SettingsTabCaption")); // NOI18N
        btnSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSettingsLayout = new javax.swing.GroupLayout(jPSettings);
        jPSettings.setLayout(jPSettingsLayout);
        jPSettingsLayout.setHorizontalGroup(
            jPSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1045, Short.MAX_VALUE))
        );
        jPSettingsLayout.setVerticalGroup(
            jPSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSettingsLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(btnSettings))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("SettingsTabCaption"), jPSettings); // NOI18N

        jPContractReport.setPreferredSize(new java.awt.Dimension(450, 64));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPContractReport, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPLaborReport)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPLaborReport, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jPContractReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLaborChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaborChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaborChargeActionPerformed

    private void btnLaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaborActionPerformed
        NavigationController.navigateToScreen(NavigationConstants.LABOR, this);
    }//GEN-LAST:event_btnLaborActionPerformed

    private void btnQuotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuotationActionPerformed
       NavigationController.navigateToScreen(NavigationConstants.QUOTATION, this);
    }//GEN-LAST:event_btnQuotationActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        NavigationController.navigateToScreen(NavigationConstants.CUSTOMER, this);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
       RegistrationService registrationService = new RegistrationServiceImpl();
       
       Arguments args = new Arguments();
       args.put("Base", NavigationConstants.DASHBOARD);
       args.put("Data", registrationService.getRegistrationDetails());
       
       NavigationController.navigateToScreen(NavigationConstants.REGISTER, this, args);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialActionPerformed
        NavigationController.navigateToScreen(NavigationConstants.MATERIAL, this);
    }//GEN-LAST:event_btnMaterialActionPerformed

    private void btnContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContractActionPerformed
        NavigationController.navigateToScreen(NavigationConstants.CONTRACT, this);
    }//GEN-LAST:event_btnContractActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContract;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLabor;
    private javax.swing.JButton btnLaborCharge;
    private javax.swing.JButton btnMaterial;
    private javax.swing.JButton btnQuotation;
    private javax.swing.JButton btnSettings;
    private javax.swing.JScrollPane jPContractReport;
    private javax.swing.JScrollPane jPLaborReport;
    private javax.swing.JPanel jPMaster;
    private javax.swing.JPanel jPSettings;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void loadContractReport() {
        DashboardServiceImpl dashboardService = new DashboardServiceImpl();
        ReportContentDto contentDto = dashboardService.getContractReport();
        JTable tblContract = new JTable(contentDto.getRowData(), contentDto.getColumnNames());
        jPContractReport.add(tblContract);
        jPContractReport.setViewportView(tblContract);
        jPContractReport.setVisible(true);
    }

    private void loadLaborWageReport() {
        DashboardServiceImpl dashboardService = new DashboardServiceImpl();
        ReportContentDto contentDto = dashboardService.getLaborWageReport();
        JTable tblContract = new JTable(contentDto.getRowData(), contentDto.getColumnNames());
        jPLaborReport.add(tblContract);
        jPLaborReport.setViewportView(tblContract);
        jPLaborReport.setVisible(true);
    }
}
